pring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.url=jdbc:postgresql://localhost/galaxyWMS
spring.datasource.username=postgres
spring.datasource.password=root
hibernate.hbm2ddl.auto="update"

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

security.enable.csrf=false